name: nexreads
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  get_cli: ^1.8.4
  google_fonts: ^4.0.4
  get: 4.6.6
  dio: 5.4.0 # Library untuk http connection
  pretty_dio_logger: ^1.3.1 # Logging Http connection
  get_storage: ^2.1.1 # Untuk get storage
  lottie: ^1.3.5 # Untuk memanggil lootie asset
  form_validator: ^2.1.1 # Untuk validasi
  flutter_rating_bar: ^4.0.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  device_info_plus: ^9.1.2
  stroke_text: ^0.0.2 
  auto_size_text: ^3.0.0
  flutter_dash: ^1.0.0
  carousel_slider: ^4.2.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

